import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";
import NavBar from '@/app/components/NavBar';
import './globals.css';

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
  params
}: {
  children: React.ReactNode;
  params: { locale: string };
}) {
  let messages;
  try {
    messages = (await import(`../locales/${params.locale}/common.json`)).default;
  } catch (error) {
    notFound();
  }

  return (
    <html lang="en">
      <body>
          <NavBar />
      </body>
    </html>
  );
}

